<?php

namespace AppBundle\Repository;

/**
 * SailorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SailorRepository extends \Doctrine\ORM\EntityRepository
{
}
